name: Generate and Sync Env Files

on:
  push:
    branches:
      - main

jobs:
  build_env_files:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate .env files
        run: |
          echo "üõ†Ô∏è Generating .env files with environment variables from GitHub Secrets and Variables..."

          cat <<EOF > .env.next
          # Next.js environment variables 
          NODE_ENV=${{ vars.NODE_ENV }}
          NEXT_HOST=${{ vars.NEXT_HOST }}
          NEXT_URL=https://${{ vars.NEXT_URL }}
          NEXT_TELEMETRY_DISABLED=1

          # Authentication
          JWT_SECRET=${{ secrets.JWT_SECRET }}

          # Database variables
          MONGO_HOST=${{ secrets.MONGO_HOST }}
          MONGO_PORT=${{ secrets.MONGO_PORT }}
          MONGO_USER=${{ secrets.MONGO_USER }}
          MONGO_PASS=${{ secrets.MONGO_PASS }}
          MONGO_DB=${{ secrets.MONGO_DB }}
          EOF

          cat <<EOF > .env.mongo
          # MongoDB environment variables
          MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_PASS }}
          MONGO_INITDB_DATABASE=${{ secrets.MONGO_DB }}
          EOF

          echo "‚úÖ .env files generated successfully!"

      - name: Setup SSH
        run: |
          echo "üìÇ Creating the .ssh directory..."
          mkdir -p ~/.ssh

          echo "üîë Extracting the private key from secrets into a file..."
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/jpd_remote_key.pem

          echo "üîí Setting strict permissions for the SSH key..."
          chmod 600 ~/.ssh/jpd_remote_key.pem

          echo "üåê Adding the server to known_hosts to prevent MITM attacks..."
          # ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files to Server
        run: |
          echo "üöÄ Syncing .env files to the server using rsync..."
          rsync -avz -e "ssh -i ~/.ssh/jpd_remote_key.pem -o StrictHostKeyChecking=no" \
            .env.next .env.mongo \
            ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }}:${{ vars.REMOTE_APP_DIR }}
